version: "3.8"

services:
  db_postgres:
    image: postgres:14.5
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_USER=postgres
      - POSTGRES_DB=db_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  django_app:
    build: .
    volumes:
      - static:/code/core/static
      - .:/code
    depends_on:
      - db_postgres
    
  nginx:
    image: nginx:1.23.1
    ports:
      - 80001:82
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - static:/code/core/static
    depends_on:
      - django_app

volumes:
  .:
  postgres_data:
  static: